#!/bin/sh

# Script to take Codimd notes and turn them into styled documents using a given style.

NOTE=$1
OUTPUT=$2
if [[ -z $3 ]]; then
    STYLE_CODE="ab" 
else
    STYLE_CODE=$3
fi

DATA_DIR="${HOME}/git/pandoc_styles/${STYLE_CODE}"

if [[ -v ${CODIMD_SERVER} ]]; then
    >&2 echo "Found CODIMD_SERVER, using ${CODIMD_SERVER}"
else
    echo "Please set CODIMD_SERVER environment variable with:
        export CODIMD_SERVER='http://hostname.org'"
fi

codimd export --md ${NOTE} - | pandoc -f markdown --data-dir=${DATA_DIR} -o ${OUTPUT} 
