#!/bin/sh

# Script to take Codimd notes and turn them into styled documents using a given style.

DEFAULT_TEMPLATE="ab"

NOTE=$1
OUTPUT=$2
if [[ -z $3 ]]; then
    STYLE_CODE=${DEFAULT_TEMPLATE}
else
    STYLE_CODE=$3
fi

DATA_DIR="${HOME}/git/pandoc_styles/${STYLE_CODE}"

if [[ -z "${CODIMD_SERVER}" ]]; then
    echo "Found CODIMD_SERVER, using ${CODIMD_SERVER}"
    exit
else
    echo "Please set CODIMD_SERVER environment variable with:
        export CODIMD_SERVER='http://hostname.org'"
fi

codimd export --md ${NOTE} - | pandoc -f markdown --data-dir=${DATA_DIR} -o ${OUTPUT} 
